spring:
  datasource:
    url: jdbc:postgresql://database:5432/it_mentor_community_platform?currentSchema=mentor_service
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: kafka:9092
    topic:
      auth-user-authenticated: auth.user.authenticated
      projects-project-created: projects.project.created
      notification-mentors-project-submitted: notifications.mentors.project.submitted

mentorservice:
  profile-service-base-url: "http://profile-service:8080"