
### 0. 201 created mentor with description and save
### ментор с таким telegramId не должен существовать
POST http://localhost:8085/api/mentor/internal/mentor
Content-Type: application/json

{
  "mentorTelegramUserId": 12345678917,
  "telegramUrl": "https://t.me/zhukovsd_1_test",
  "description": {
    "name": "Sergey Zhukov",
    "cost": "PAID",
    "description": "Мои услуги - https://zhukovsd.it/services/"
  },
  "programmingLanguages": [
    "Java",
    "Python",
    "Kotlin"
  ],
  "services": [
    "менторство по поиску работы",
    "консультации"
  ]
}

> {%
    client.test("Status is 201", function () {
        client.assert(response.status === 201, "Expected 201, got " + response.status);
    });

    client.global.set("mentorTelegramUserId", String(response.body.mentorTelegramUserId));
%}



### 1. 200-Successfully created mentor with description
PATCH http://localhost:8085/api/mentor/mentor/description
Content-Type: application/json
X-Telegram-User-Id: {{mentorTelegramUserId}}

{
  "name": "Sergey Zhukov",
  "cost": "FREE",
  "description": "Мои услуги - https://zhukovsd.it/services/"
}

> {%
    client.test("Status is 200", function () {
        client.assert(response.status === 200, "Expected 200, got " + response.status);
    });

    client.test("Description matches request", function () {
        client.assert(response.body.name === "Sergey Zhukov", "Wrong name");
        client.assert(response.body.cost === "FREE", "Wrong cost");
    });
%}

### 2. 400-validation failed (Description is required)
PATCH http://localhost:8085/api/mentor/mentor/description
Content-Type: application/json

{
}

> {%
    client.test("Status is 400", function () {
        client.assert(response.status === 400, "Expected 400, got " + response.status);
    });
%}


### 3. 400-validation failed (Failed parse TelegramId)
PATCH http://localhost:8085/api/mentor/mentor/description
Content-Type: application/json
X-Telegram-User-Id: ыы1234

{
  "name": "name",
  "cost": "PAID",
  "description": "Мои услуги - https://zhukovsd.it/services/"
}

> {%
    client.test("Status is 400", function () {
        client.assert(response.status === 400, "Expected 400, got " + response.status);
    });

    client.test("Error message mentions invalid id", function () {
        client.assert(response.body.message.includes("numeric"),
            "Unexpected message: " + response.body.message);
    });
%}

### 4. Empty fields do not erase the old ones
PATCH http://localhost:8085/api/mentor/mentor/description
Content-Type: application/json
X-Telegram-User-Id: {{mentorTelegramUserId}}

{
  "description": "Мои услуги - https://vk.com/"
}


> {%
    client.test("Status is 200", function () {
        client.assert(response.status === 200, "Expected 200, got " + response.status);
    });

    client.test("Name was not erased", function () {
        client.assert(response.body.name === "Sergey Zhukov",
            "Expected name to stay 'Sergey Zhukov', got: " + response.body.description.name);
        client.assert(response.body.cost === "FREE",
            "Expected cost to stay 'FREE', got: " + response.body.cost);
        client.assert(response.body.description === "Мои услуги - https://vk.com/",
            "Expected cost to stay 'Мои услуги - https://vk.com/', got: " + response.body.description.description);
    });
%}


### 5. 4034 failed (User is not mentor)
PATCH http://localhost:8085/api/mentor/mentor/description
Content-Type: application/json
X-Telegram-User-Id: 1234

{
  "name": "",
  "description": "Мои услуги - https://zhukovsd.it/services/"
}

> {%
    client.test("Status is 403", function () {
        client.assert(response.status === 403, "Expected 403, got " + response.status);
    });
%}

